python main_ipu.py 	\
       	--cfg configs/swin/swin_large_patch4_window7_224_22kto1k_finetune.yaml \
	--pretrained  swin_large_patch4_window7_224_22k.pth \
	--local_rank 0					     \
	--batch-size 2					     \
	--run-ipu					     \
       	--data-path /localdata/cn-customer-engineering/zhiweit/ai-datasets/datasets/imagenet/raw/imagenet-raw-data/  \
	--executable-cache-dir ./cache	\
	--data imagenet			\
	--accumulation-steps 128 \
	--replication-factor 2
